version: "3.8"

services:
  web:
    build:
      context: ../Project
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - todo-network
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo-network

volumes:
  db_data:

networks:
  todo-network:
